Host IP address removed from header response in createsession api
salonisrivastava12/ODIM pull request #1
Opened 2023-07-25 12:54 UTC by salonisrivastava12

Host IP address removed from header response in createsession api

2023-07-25 13:33 UTC, jeevan-kamkar requested changes
address the requested changes

2023-07-25 13:33 UTC, jeevan-kamkar commented on svc-account-session/session/create.go
> +		// "Location":      "</redfish/v1/SessionService/Sessions/" + sess.ID + "/>; rel=self",
remove the commented code

2023-07-26 04:29 UTC, jeevan-kamkar approved these changes

2023-07-26 06:06 UTC, mohamed-shahid-afrid approved these changes

2023-07-26 06:06 UTC, mohamed-shahid-afrid commented on svc-account-session/session/create.go
> +		// "Location":      "</redfish/v1/SessionService/Sessions/" + sess.ID + "/>; rel=self",
remove the comment

2023-07-26 07:54 UTC, merged